export const es = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Conocimiento Colaborativo.",
    m2: "Compartiendo el conocimiento de todos usando tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Responder",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadísticas",
    m8: "Configuración",
    m9: "Login",
    m10: "Login con Metamask",
    m11: "Logout",
    m12: "Registro",
    m13: "Contraseña",
    m14: "Wallet sin Metamask",
    m15: "Semilla (12 palabras)",
};

export const en = {
    m0: "Language:",
    m1: "ESBRINA CHAIN - Collaborative Knowledge System",
    m2: "Sharing everyone's knowledge with blockchain technology.",
    m3: "Asking",
    m4: "Answering",
    m5: "Voting",
    m6: "Opinions",
    m7: "Statistics",
    m8: "Configuration",
    m9: "Login",
    m10: "Login with Metamask",
    m11: "Logout",
    m12: "Register",
    m13: "Password",
    m14: "Wallet without Metamask",
    m15: "Seed (12 words)",
};

export const cat = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Coneixement Col.laboratiu.",
    m2: "Compartint el coneixement de tots amb tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Respondre",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadístiques",
    m8: "Configuració",
    m9: "Login",
    m10: "Login amb Metamask",
    m11: "Logout",
    m12: "Registrar-se",
    m13: "Contrasenya",
    m14: "Wallet sense Metamask",
    m15: "Llavor (12 paraules)",

};

