export const es = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Conocimiento Colaborativo.",
    m2: "Compartiendo el conocimiento de todos usando tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Responder",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadísticas",
    m8: "Configuración",
    m9: "Login",
    m10: "Login con Metamask",
    m11: "Logout",
    m12: "Registro",
    m13: "Contraseña",
    m14: "Wallet sin Metamask",
    m15: "Semilla (12 palabras)",
    m16: "Email",
    m17: "Registro de usuarios",
    m18: "Registrar nuevo usuario",
    m20: "Alias",
    m21: "Por favor, introduzca una dirección de correo electrónico correcta!",
    m22: "Usted tiene ya una cuenta creada en Esbrinachain!",
    m23: "Pulse 'Borrar cuenta' para eliminar esta cuenta",
    m24: "Borrar cuenta",
    m25: "Realizar una Nueva Pregunta",
    m26: "Responder",
    m27: "Sólo 1 vez",
    m28: "Votar",
    m29: "Datos más recientes",
    m30: "Coste 50%",
    m31: "Ver\nSolución",
    m32: "(excepto autor)",
    m33: "Tiempo de Respuesta",
    m34: "Período de Votación ",
    m35: "Cupo de Respuestas",
    m36: "Bote acumulado",
    m37: "votos",
    m38: "Reputación en el Sistema",
    m39: "Usuario",
    m40: "Reputación",
    m41: "Subir recompensa!",
    m42: "intentos",
    m43: "Autor:",
    m44: "Fecha:",
    m45: "Estado: ",
    m46: "Recompensa:",
    m47: "Fecha Votación",
    m48: "Enviando Tx para crear la respuesta ...",
    m49: "Tx exitosa ...",
    m50: "Error o cancelación de Tx ...",
    m51: "Este usuario ha respondido anteriormente a esta pregunta...",
    m52: "Este usuario es el autor de esta pregunta...",
    m53: "Esta pregunta no está abierta para responder...",
    m54: "Efectuando el pago para saber el ganador de la pregunta ...",
    m55: "Efectuando subida de recompensa ...",
    m56: "Las preguntas en estado 'consulta' o 'anulada' no pueden incrementar la recompensa",
    m57: "Enviando Tx para crear la pregunta...",
    m58: "Precio del Gas: ",
    m59: "Límite de Gas Estimado: ",
    m60: "Enviando Tx de voto...",
    m61: "Se ha intentado votar y la pregunta ha cambiado ha estado 'consulta'",
    m62: "Se ha intentado votar y la pregunta ha cambiado ha estado 'anulada'",
    m63: "Actualizando el voto en el sistema...",
    m64: "Se ha intentado responder y la pregunta ha canviado a 'votando'",
    m65: "Se ha intentado responder y la pregunta ha canviado a 'anulada'",
    m66: "El autor de una pregunta no puede votarla.",
    m67: "Si ha respondido a la pregunta, no puede votarla",
    m68: "Solo se puede votar 1 respuesta.",
    m69: "12 Palabras reservadas...",
    m70: "Enviando Tx - Obteniendo las respuestas más votadas...",
    m71: "Coste = ",
    m72: "",
    m73: "",
    m74: "",
    m75: "",
    m76: "",
    m77: "",
};

export const en = {
    m0: "Language:",
    m1: "ESBRINA CHAIN - Collaborative Knowledge System",
    m2: "Sharing everyone's knowledge with blockchain technology.",
    m3: "Asking",
    m4: "Answering",
    m5: "Voting",
    m6: "Opinions",
    m7: "Statistics",
    m8: "Configuration",
    m9: "Login",
    m10: "Login with Metamask",
    m11: "Logout",
    m12: "Register",
    m13: "Password",
    m14: "Wallet without Metamask",
    m15: "Seed (12 words)",
    m16: "Email",
    m17: "User Recording",
    m18: "Register a new user",
    m20: "Alias",
    m21: "Please enter a valid email address!",
    m22: "You have an account in Esbrinachain yet!",
    m23: "Press 'Erase account' to eliminate this account ",
    m24: "Erase account",
    m25: "Make a New Question",
    m26: "Post a New Answer",
    m27: "Only one answer by question",
    m28: "To Vote",
    m29: "Most recent data",
    m30: "Cost 50%",
    m31: "Show\nSolution",
    m32: "(except owner",
    m33: "Response Time",
    m34: "Voting Period",
    m35: "Response Quota",
    m36: "Progressive Jackpot",
    m37: "votes",
    m38: "Reputation on the System",
    m39: "User",
    m40: "Reputation",
    m41: "Go up, reward!",
    m42: "attemps",
    m43: "Author:",
    m44: "Date:",
    m45: "State: ",
    m46: "Reward:",
    m47: "Ballot Date",
    m48: "Sending Tx to create an answer ...",
    m49: "Tx successful ...",
    m50: "Error or Tx reverted ...",
    m51: "This user already has answered this question...",
    m52: "This user is the author of this question...",
    m53: "This question not is opened to answer...",
    m54: "Doing the payment to know the winner answer...",
    m55: "Making a raise of the reward...",
    m56: "Questions in 'consulta' or 'anulada' state cannot up the reward.",
    m57: "Sending Tx to make the question...",
    m58: "Gas Price: ",
    m59: "Gas Limit Estimated: ",
    m60: "Sending Tx to Vote...",
    m61: "After trying to vote the question has changed to 'consulta' state",
    m62: "After trying to vote the question has changed to 'anulada' state",
    m63: "Updating vote to the system...",
    m64: "When answering the question has changed to 'votando' state",
    m65: "When answering the question has changed to 'anulada' state",
    m66: "If you are author's question, you can't vote.",
    m67: "If you answered a question, you can't vote.",
    m68: "One vote per question is permitted.",
    m69: "12 reserved words...",
    m70: "Sending Tx - getting the most voted answers...",
    m71: "Cost = ",
    m72: "",
    m73: "",
    m74: "",
    m75: "",
    m76: "",
    m77: "",
};

export const cat = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Coneixement Col.laboratiu.",
    m2: "Compartint el coneixement de tots amb tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Respondre",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadístiques",
    m8: "Configuració",
    m9: "Login",
    m10: "Login amb Metamask",
    m11: "Logout",
    m12: "Registrar-se",
    m13: "Contrasenya",
    m14: "Wallet sense Metamask",
    m15: "Llavor (12 paraules)",
    m16: "Email",
    m17: "Registre d'Usuaris",
    m18: "Registrar un nou usuari",
    m20: "Àlies",
    m21: "Si us plau, entri una adreça de correu correcta!",
    m22: "Voste ja té un compte creat a Esbrinachain!",
    m23: "Premi 'Esborrar compte' per eliminar el compte.",
    m24: "Erase account",
    m25: "Crear una Nova Pregunta",
    m26: "Respondre",
    m27: "Només 1 resposta per pregunta",
    m28: "Votar",
    m29: "Dades més recents",
    m30: "Cost 50%",
    m31: "Veure\nSolució",
    m32: "(no autor)",
    m33: "Temps de Resposta",
    m34: "Període de Votació",
    m35: "Quota de Respostes",
    m36: "Pot acumulat",
    m37: "vots",
    m38: "Reputació al Sistema",
    m39: "Usuari",
    m40: "Reputació",
    m41: "Pujar la recompensa!",
    m42: "intents",
    m43: "Autor:",
    m44: "Data:",
    m45: "Estat: ",
    m46: "Recompensa:",
    m47: "Data Votació",
    m48: "Enviant Tx per crear la resposta ...",
    m49: "Tx exitosa ...",
    m50: "Error o cancel·lació de Tx ...",
    m51: "Aquest usuari ja ha respost anteriorment a aquesta pregunta...",
    m52: "This user is the author of this question",
    m53: "Aquesta pregunta no està oberta per respondre...",
    m54: "Efectuant el pagament per saber el guanyador de la pregunta ...",
    m55: "Fent una pujada de recompensa...",
    m56: "Preguntes en estat de 'consulta' o 'anul·lada', no poden incrementar la recompensa.",
    m57: "Enviant Tx per crear la pregunta...",
    m58: "Preu del Gas: ",
    m59: "Limit de Gas Estima: ",
    m60: "Enviant Tx de Vot...",
    m61: "Després d'intentar votar la pregunta a canviat a l'estat 'consulta'",
    m62: "Després d'intentar votar la pregunta a canviat a l'estat 'anulada'",
    m63: "Actualitzant el vot en el sistema...",
    m64: "Al respondre a la pregunta, ha canviat a estat 'votando'",
    m65: "Al respondre a la pregunta, ha canviat a estat 'anulada'",
    m66: "L'autor de la pregunta, no pot votarla",
    m67: "Si ha contestat a la pregunta, no pot votar-la.",
    m68: "Només es pot votar per una resposta.",
    m69: "12 paraules reservades...",
    m70: "Enviant Tx - obtenint les respostes més votades...",
    m71: "Cost = ",
    m72: "",
    m73: "",
    m74: "",
    m75: "",
    m76: "",
    m77: "",
    
};

