export const es = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Conocimiento Colaborativo.",
    m2: "Compartiendo el conocimiento de todos usando tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Responder",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadísticas",
    m8: "Configuración",
    m9: "Login",
    m10: "Login con Metamask",
    m11: "Logout",
    m12: "Registro",
    m13: "Contraseña",
    m14: "Wallet sin Metamask",
    m15: "Semilla (12 palabras)",
    m16: "Email",
    m17: "Registro de usuarios",
    m18: "Registrar nuevo usuario",
    m20: "Alias",
    m21: "Por favor, introduzca una dirección de correo electrónico correcta!",
    m22: "Usted tiene ya una cuenta creada en Esbrinachain!",
    m23: "Pulse 'Borrar cuenta' para eliminar esta cuenta",
    m24: "Borrar cuenta",
    m25: "Realizar una Nueva Pregunta",
    m26: "Responder",
    m27: "Sólo 1 vez",
    m28: "Votar",
    m29: "Datos más recientes",
    m30: "Coste 50%",
    m31: "Solución",
    m32: "(excepto autor)",
    m33: "Tiempo de Respuesta",
    m34: "Período de Votación ",
    m35: "Cupo de Respuestas",
    m36: "Bote acumulado",
    m37: "votos",
    m38: "Reputación en el Sistema",
    m39: "",
    m40: "",
};

export const en = {
    m0: "Language:",
    m1: "ESBRINA CHAIN - Collaborative Knowledge System",
    m2: "Sharing everyone's knowledge with blockchain technology.",
    m3: "Asking",
    m4: "Answering",
    m5: "Voting",
    m6: "Opinions",
    m7: "Statistics",
    m8: "Configuration",
    m9: "Login",
    m10: "Login with Metamask",
    m11: "Logout",
    m12: "Register",
    m13: "Password",
    m14: "Wallet without Metamask",
    m15: "Seed (12 words)",
    m16: "Email",
    m17: "User Recording",
    m18: "Register a new user",
    m20: "Alias",
    m21: "Please enter a valid email address!",
    m22: "You have an account in Esbrinachain yet!",
    m23: "Press 'Erase account' to eliminate this account ",
    m24: "Erase account",
    m25: "Make a New Question",
    m26: "Post a New Answer",
    m27: "Only one answer by question",
    m28: "To Vote",
    m29: "Most recent data",
    m30: "Cost 50%",
    m31: "Solution",
    m32: "(except owner",
    m33: "Response Time",
    m34: "Voting Period",
    m35: "Response Quota",
    m36: "Progressive Jackpot",
    m37: "votes",
    m38: "Reputation on the System",
    m39: "",
    m40: ""
};

export const cat = {
    m0: "Idioma:",
    m1: "ESBRINA CHAIN - Sistema de Coneixement Col.laboratiu.",
    m2: "Compartint el coneixement de tots amb tecnología Blockchain.",
    m3: "Preguntar",
    m4: "Respondre",
    m5: "Votar",
    m6: "Opinar",
    m7: "Estadístiques",
    m8: "Configuració",
    m9: "Login",
    m10: "Login amb Metamask",
    m11: "Logout",
    m12: "Registrar-se",
    m13: "Contrasenya",
    m14: "Wallet sense Metamask",
    m15: "Llavor (12 paraules)",
    m16: "Email",
    m17: "Registre d'Usuaris",
    m18: "Registrar un nou usuari",
    m20: "Àlies",
    m21: "Si us plau, entri una adreça de correu correcta!",
    m22: "Voste ja té un compte creat a Esbrinachain!",
    m23: "Premi 'Esborrar compte' per eliminar el compte.",
    m24: "Erase account",
    m25: "Crear una Nova Pregunta",
    m26: "Respondre",
    m27: "Només 1 resposta per pregunta",
    m28: "Votar",
    m29: "Dades més recents",
    m30: "Cost 50%",
    m31: "Solució",
    m32: "(no autor)",
    m33: "Temps de Resposta",
    m34: "Període de Votació",
    m35: "Quota de Respostes",
    m36: "Pot acumulat",
    m37: "vots",
    m38: "Reputació al Sistema",
    m39: "",
    m40: ""
};

